# Generated by Django 4.2.7 on 2023-12-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=30)),
                ("body", models.CharField(max_length=30)),
                ("junior_id", models.IntegerField()),
                ("senior_id", models.IntegerField(null=True)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "issues",
            },
        ),
        migrations.CreateModel(
            name="Massage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("content", models.CharField(max_length=100)),
                ("author_id", models.IntegerField()),
                ("issues_id", models.IntegerField()),
            ],
            options={
                "db_table": "issues_massages",
            },
        ),
    ]
