# Generated by Django 4.2.7 on 2023-12-01 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Issues",
        ),
    ]
